In [1]:
#Importación de librerías
import numpy as np 
import gym
import random
from IPython.display import clear_output
import time

In [2]:
#Crear ambiente
env = gym.make("Taxi-v3")
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [3]:
#Crear Q-table e inicializarlo

action_size = env.action_space.n
print("Action size", action_size)

state_size = env.observation_space.n
print("Sate size", state_size)

Action size 6
Sate size 500


In [4]:
q_table = np.zeros((state_size, action_size))
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
#Crear los hyperparameters

#Episodios totales
juegos = 50000
#Episodios de prueba
juegos_prueba = 100
#Máximo de pasos en el episodio
max_steps = 99

learning_rate = 0.1
discount_rate = 0.6

#Parámetros de exploración
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
#Cuánto va a ir disminuyendo el epsilon
decay_rate = 0.01


In [6]:
#Q-learning 

for juego in range(juegos):
    state = env.reset()
    step = 0
    done = False

    for step in range(max_steps):
        #Para escoger una acción con un número aleatorio
        num_random = random.uniform(0,1)

        if num_random > epsilon:
            action = np.argmax(q_table[state,:])

        else:
            action = env.action_space.sample()

        #Devolver el estado y la recompensa
        new_state, recompensa, done, info = env.step(action)    

        #Actualizar
        q_table[state, action] = q_table[state, action] + learning_rate * (recompensa + discount_rate * np.max(q_table[new_state, :]) - q_table[state, action])

        #El nuevo estado
        state = new_state

        #Si la respuesta es done, se termina el episodio
        if done == True:
            break
    juego += 1

    #Reducir epsilon
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * juego)


In [14]:
#Taxi
env.reset()

recompensas = []

for juego in range(juegos_prueba):
    state = env.reset()
    step = 0
    done = False
    recompensas_total = 0
    print ("Juego", juego)

    for step in range(max_steps):
        env.render()

        action = np.argmax(q_table[state, :])

        new_state, recompensa, done, info = env.step(action)

        recompensas_total += recompensa

        if done:
            recompensas.append(recompensas_total)
            print("Puntaje", recompensas_total)
            break
        state = new_state
env.close()

print("Puntaje total: " + str(sum(recompensas)/juegos_prueba))


Juego 0
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| :_: : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : :_: : |
| | : | : |
|Y| 

In [7]:
casos_favorable = 0
for juego in range(juegos_prueba):
    recompensas_total = 0
    state = env.reset()

    while True:
        clear_output(wait = True)
        print(f'Episode {juego+1}')

        env.render()
        action = np.argmax(q_table[state])
        state, recompensa, done, info = env.step(action)
        recompensas_total += recompensa
        print(f'Recompensa del paso: {recompensa}')
        print(f'Recompensa final: {recompensas_total}')
        
        time.sleep(0.3)
        
        if done:
            print('Juego terminado')
            if recompensas_total > 0 :
                casos_favorable += 1
            time.sleep(2)
            break

print("Porcentaje de éxito:", (casos_favorable/juegos_prueba)*100)

Episode 87
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
Recompensa del paso: 20
Recompensa final: 10
Juego terminado


KeyboardInterrupt: 